ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter
#Add-Begin by zhikui.li@tcl.com for porting SMD sensor driver
#obj-y := mc34xx.o
obj-y := mc3xxx.o
#Add-END by zhikui.li@tcl.com for porting SMD sensor driver

