

name: Build Kernel

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "tb8765ap1_bsp_debug_defconfig"
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    # Rest of your steps...

    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

    - name: Build Kernel
      run: |
        if [[ ! -d gcc ]]; then
          git clone https://github.com/Skyrimus/arm-linux-gnueabihf-linaro-6.3.1-mt6580 gcc
        fi
        mkdir -p out
        export CROSS_COMPILE=${PWD}/gcc/bin/arm-linux-gnueabihf-
        export USE_CCACHE=1
        export ARCH=arm
        export SUBARCH=arm
        export TARGET=out
        make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE tb8765ap1_bsp_debug_defconfig | tee -a Defconfig.log
        make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j8 | tee -a Kernel.log

    - name: Upload zImage-dtb
      run: |
        curl -T out/arch/arm/boot/zImage-dtb https://bashupload.com/ --output upload_link
        UPLOAD_LINK=$(< upload_link)
        echo "Uploaded file link: $UPLOAD_LINK"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
